name: Condosuite Temp - Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - DEV
          - PRO

permissions:
  id-token: write
  actions: read
  contents: read

jobs:
  build:
    uses: condoconta-tech/githubworkflows/.github/workflows/build.yaml@v0.0.7
    with:
      image: is-condosuite-temp
      dockerfile: docker/Dockerfile.prod-single
    secrets:
      aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
  deploy:
    needs: [build]
    uses: condoconta-tech/githubworkflows/.github/workflows/deploy.yaml@v0.0.7
    with:
      deploy-name: open-webui
      namespace: open-webui
      values-path: k8s
      env:  ${{ inputs.environment }}
      tag: ${{ needs.build.outputs.tag }}
    secrets:
      aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
